#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SIDECAR = ROOT / "sidecar"
OUTPUT_PATH = ROOT / "sidecar/autoskill/observatory/src/generated/observatoryClient.ts"
ADMIN_API_PREFIX = "/admin/api/v1"
HTTP_METHODS = ("get", "post", "put", "patch", "delete")


def load_openapi_schema() -> dict[str, Any]:
    sys.path.insert(0, str(SIDECAR))
    from autoskill.api.app import create_app

    return create_app(api_surface="observatory").openapi()


def build_client_source(schema: dict[str, Any]) -> str:
    routes = _admin_routes(schema)
    route_paths = sorted({route["path"] for route in routes})
    path_union = " | ".join(json.dumps(path) for path in route_paths)
    methods = sorted({route["method"] for route in routes})
    method_union = " | ".join(json.dumps(method) for method in methods)
    routes_json = json.dumps(routes, indent=2, sort_keys=True)
    paths_json = json.dumps(route_paths, indent=2)
    return f"""// Generated by scripts/generate_observatory_openapi_client.py.
// Do not edit by hand.

export const OBSERVATORY_API_BASE_PATH = {json.dumps(ADMIN_API_PREFIX)};

export const OBSERVATORY_ROUTE_PATHS = {paths_json} as const;

export type ObservatoryRoutePath = {path_union};
export type ObservatoryHttpMethod = {method_union};

export type ObservatoryRoute = {{
  method: ObservatoryHttpMethod;
  path: ObservatoryRoutePath;
  operationId: string;
  summary: string;
  tags: readonly string[];
}};

export const OBSERVATORY_ROUTES = {routes_json} as const satisfies readonly ObservatoryRoute[];

const ROUTE_SET = new Set<string>(OBSERVATORY_ROUTE_PATHS);

export function isKnownAdminRoutePath(path: string): path is ObservatoryRoutePath {{
  return ROUTE_SET.has(path);
}}

export function adminApiPath(
  path: ObservatoryRoutePath,
  params: Record<string, string | number | boolean> = {{}}
): string {{
  let rendered: string = path;
  for (const [key, value] of Object.entries(params)) {{
    rendered = rendered.replace(`{{${{key}}}}`, encodeURIComponent(String(value)));
  }}
  return rendered;
}}
"""


def write_client(*, check: bool = False) -> int:
    source = build_client_source(load_openapi_schema())
    if check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != source:
            print(f"{OUTPUT_PATH} is stale; rerun {Path(__file__).name}", file=sys.stderr)
            return 1
        return 0
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(source, encoding="utf-8")
    return 0


def _admin_routes(schema: dict[str, Any]) -> list[dict[str, Any]]:
    routes: list[dict[str, Any]] = []
    for raw_path, methods in sorted(schema.get("paths", {}).items()):
        if not raw_path.startswith(ADMIN_API_PREFIX):
            continue
        relative_path = raw_path.removeprefix(ADMIN_API_PREFIX) or "/"
        for method in HTTP_METHODS:
            operation = methods.get(method)
            if not isinstance(operation, dict):
                continue
            routes.append(
                {
                    "method": method.upper(),
                    "path": relative_path,
                    "operationId": str(operation.get("operationId") or ""),
                    "summary": str(operation.get("summary") or ""),
                    "tags": [str(tag) for tag in operation.get("tags", [])],
                }
            )
    return routes


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate the Observatory frontend admin API route client from FastAPI OpenAPI."
        ),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated client is stale.",
    )
    return parser.parse_args()


def main() -> int:
    return write_client(check=parse_args().check)


if __name__ == "__main__":
    raise SystemExit(main())
